// tldrawの初期ドキュメントテンプレート
// Note: tldraw v4では、テキストシェイプの初期化方法が変更されています
// スナップショット内でテキストシェイプを作成する場合は、エディターがマウントされた後に
// プログラム的にテキストを追加する方が安全です

export function getWelcomeTemplate() {
  return {
    store: {
      'document:document': {
        gridSize: 10,
        name: '',
        meta: {},
        id: 'document:document',
        typeName: 'document',
      },
      'page:page': {
        meta: {},
        id: 'page:page',
        name: 'Page 1',
        index: 'a1',
        typeName: 'page',
      },
      // Tldraw v4では、スナップショット内でテキストシェイプのtextプロパティは使用できません
      // テキストシェイプはエディターがマウントされた後にプログラム的に追加します
      'shape:step1-frame': {
        x: 150,
        y: 300,
        rotation: 0,
        isLocked: false,
        opacity: 1,
        meta: {},
        id: 'shape:step1-frame',
        type: 'geo',
        props: {
          w: 400,
          h: 200,
          geo: 'rectangle',
          color: 'light-blue',
          labelColor: 'black',
          fill: 'solid',
          dash: 'dashed',
          size: 'm',
          font: 'sans',
          text: 'STEP 1\n\nSelect Items\n\nWhen in chat mode 💬, drag a box around your items to activate chat window',
          align: 'start',
          verticalAlign: 'start',
          growY: 0,
          url: '',
          scale: 1,
        },
        parentId: 'page:page',
        index: 'a3',
        typeName: 'shape',
      },
      'shape:step2-frame': {
        x: 150,
        y: 550,
        rotation: 0,
        isLocked: false,
        opacity: 1,
        meta: {},
        id: 'shape:step2-frame',
        type: 'geo',
        props: {
          w: 400,
          h: 220,
          geo: 'rectangle',
          color: 'light-green',
          labelColor: 'black',
          fill: 'solid',
          dash: 'dashed',
          size: 'm',
          font: 'sans',
          text: 'STEP 2\n\nType and Run\n\nType your idea, for example:\n"Add prominent horns to my logo. Light mint green background. Add text: Monster Agent below with same font style from the image 2"\n\nRun ⌘↵ to get result instantly',
          align: 'start',
          verticalAlign: 'start',
          growY: 0,
          url: '',
          scale: 1,
        },
        parentId: 'page:page',
        index: 'a4',
        typeName: 'shape',
      },
      'shape:step3-frame': {
        x: 150,
        y: 830,
        rotation: 0,
        isLocked: false,
        opacity: 1,
        meta: {},
        id: 'shape:step3-frame',
        type: 'geo',
        props: {
          w: 400,
          h: 180,
          geo: 'rectangle',
          color: 'light-green',
          labelColor: 'black',
          fill: 'solid',
          dash: 'dashed',
          size: 'm',
          font: 'sans',
          text: 'STEP 3\n\nExplore More\n\nTo exit chat mode, press Esc.\nFor inspirations, click 💡 for more templates\nYou can also start creating from the agent panel!',
          align: 'start',
          verticalAlign: 'start',
          growY: 0,
          url: '',
          scale: 1,
        },
        parentId: 'page:page',
        index: 'a5',
        typeName: 'shape',
      },
    },
    schema: {
      schemaVersion: 2,
      sequences: {
        'com.tldraw.store': 4,
        'com.tldraw.asset': 1,
        'com.tldraw.camera': 1,
        'com.tldraw.document': 2,
        'com.tldraw.instance': 25,
        'com.tldraw.instance_page_state': 5,
        'com.tldraw.page': 1,
        'com.tldraw.instance_presence': 5,
        'com.tldraw.pointer': 1,
        'com.tldraw.shape': 4,
        'com.tldraw.asset.bookmark': 2,
        'com.tldraw.asset.image': 5,
        'com.tldraw.asset.video': 5,
        'com.tldraw.shape.group': 0,
        'com.tldraw.shape.text': 2,
        'com.tldraw.shape.bookmark': 2,
        'com.tldraw.shape.draw': 2,
        'com.tldraw.shape.geo': 9,
        'com.tldraw.shape.note': 8,
        'com.tldraw.shape.line': 5,
        'com.tldraw.shape.frame': 0,
        'com.tldraw.shape.arrow': 5,
        'com.tldraw.shape.highlight': 1,
        'com.tldraw.shape.embed': 4,
        'com.tldraw.shape.image': 4,
        'com.tldraw.shape.video': 2,
        'com.tldraw.binding.arrow': 0,
      },
    },
  };
}

export function getBlankTemplate() {
  return {
    store: {
      'document:document': {
        gridSize: 10,
        name: '',
        meta: {},
        id: 'document:document',
        typeName: 'document',
      },
      'page:page': {
        meta: {},
        id: 'page:page',
        name: 'Page 1',
        index: 'a1',
        typeName: 'page',
      },
    },
    schema: {
      schemaVersion: 2,
      sequences: {
        'com.tldraw.store': 4,
        'com.tldraw.asset': 1,
        'com.tldraw.camera': 1,
        'com.tldraw.document': 2,
        'com.tldraw.instance': 25,
        'com.tldraw.instance_page_state': 5,
        'com.tldraw.page': 1,
        'com.tldraw.instance_presence': 5,
        'com.tldraw.pointer': 1,
        'com.tldraw.shape': 4,
        'com.tldraw.asset.bookmark': 2,
        'com.tldraw.asset.image': 5,
        'com.tldraw.asset.video': 5,
        'com.tldraw.shape.group': 0,
        'com.tldraw.shape.text': 2,
        'com.tldraw.shape.bookmark': 2,
        'com.tldraw.shape.draw': 2,
        'com.tldraw.shape.geo': 9,
        'com.tldraw.shape.note': 8,
        'com.tldraw.shape.line': 5,
        'com.tldraw.shape.frame': 0,
        'com.tldraw.shape.arrow': 5,
        'com.tldraw.shape.highlight': 1,
        'com.tldraw.shape.embed': 4,
        'com.tldraw.shape.image': 4,
        'com.tldraw.shape.video': 2,
        'com.tldraw.binding.arrow': 0,
      },
    },
  };
}
